### ISSUE TITLE
[Tracking issue] SRS

### ISSUE THREAD

**Issue by jjmountain** [Wheely-Good/wheels-expo#22]
# SRS Roadmap

- [ ] First pass - https://github.com/Wheely-Good/wheels-expo/pull/20
- [ ] Figure out data models
- [ ] Do not remove new cards from study session until user has confirmed they recognize them
- [ ] Add ability for users to mark a word as known
- [ ] Switch interval timing back to real-time (days)
- [ ] Add visualizations for progress
- [ ] Improve flashcard styling (positioning, animations, etc.)
- [ ] Allow users to go back to the previous card with back button etc. (e.g in case of mistaken press)
