### ISSUE TITLE
[Tracking issue] Authorization

### ISSUE THREAD

**Issue by jjmountain** [Wheely-Good/wheels-expo#7]
- [x] Implement basic auth with sign up / sign in
- [x] Create sign in / sign out pages
- [ ] Style ☝️ pages
- [ ] Add native alerts for errors 
- [x] Add message saying to check the email

## Account Page
- [ ] Complete account page and allow users to save info and upload a picture (see this [tutorial](https://supabase.com/docs/guides/getting-started/tutorials/with-expo-react-native?queryGroups=auth-store&auth-store=async-storage))
